import subprocess
import sys
import os.path
import fileinput
import json

from enum import Enum


def main(argv):
    configname: str = argv[1]
    pathname: str = argv[2]

    print(configname)
    trap_entry_name: str = "trap_entry"
    list_name_suffix: str = "vectors"
    item_name_suffix: str = "vector"

    with open(configname, mode="r") as configfile:
        config = json.loads(configfile.read())
        trap_entry_name = config["trap_entry_name"]
        list_name_suffix = config["list_name_suffix"]
        item_name_suffix = config["item_name_prefix"]

    with open(pathname, mode="w") as fp:
        fp.writelines(["# generated by gvectors.py\n", "# handlers\n"])
        fp.write(".globl "+trap_entry_name+"\n")
        for i in range(0, 256):
            iname: str = str(i)
            fp.write(".globl "+item_name_suffix + iname+"\n")
            fp.write(item_name_suffix + iname + ":\n")
            if not (i == 8 or (i >= 10 and i <= 14) or i == 17):
                fp.write("  push $0\n")

            fp.write("  push $" + iname+"\n")
            fp.write("  jmp "+trap_entry_name+"\n")

        fp.write("\n# vector table\n")
        fp.write(".data\n")
        fp.write(".globl "+list_name_suffix+"\n")
        fp.write(list_name_suffix+":\n")
        for i in range(0, 256):
            iname: str = str(i)
            fp.write("  .quad "+item_name_suffix + iname+"\n")
    pass


if __name__ == "__main__":
    main(sys.argv)
