import subprocess
import sys
import os.path
import fileinput
from enum import Enum


def main(argv):
    pathname: str = argv[1]
    with open(pathname, mode="w") as fp:
        fp.writelines(["# generated by gvectors.py\n", "# handlers\n"])
        fp.write(".globl trapsentry\n")
        for i in range(0, 256):
            iname: str = str(i)
            fp.write(".globl vector" + iname+"\n")
            fp.write("vector" + iname + ":\n")
            if not (i == 8 or (i >= 10 and i <= 14) or i == 17):
                fp.write("  push $0\n")

            fp.write("  push $" + iname+"\n")
            fp.write("  jmp trapsentry\n")

        fp.write("\n# vector table\n")
        fp.write(".data\n")
        fp.write(".globl vectors\n")
        fp.write("vectors:\n")
        for i in range(0, 256):
            iname: str = str(i)
            fp.write("  .quad vector"+iname+"\n")
    pass


if __name__ == "__main__":
    main(sys.argv)
