import subprocess
import sys
import os.path
import fileinput
from enum import Enum


def main(argv):
    pathname: str = argv[1]
    with open(pathname, mode="w") as fp:
        fp.writelines(["# generated by gvectors.py", "# handlers"])
        fp.write(".globl alltraps")
        for i in range(0, 256):
            iname: str = str(i)
            fp.write(".globl vector" + iname)
            fp.write("vector" + iname + ":")
            if not (i == 8 or (i >= 10 and i <= 14) or i == 17):
                fp.write("  push $0")

            fp.write(" push $" + iname)
            fp.write("  jmp alltraps")

        fp.write("\n# vector table")
        fp.write(".data")
        fp.write(".globl vectors")
        fp.write("vectors:")
        for i in range(0, 256):
            iname: str = str(i)
            fp.write("  .quad vector"+iname)
    pass


if __name__ == "__main__":
    main(sys.argv)
