
#include "sys/bootmm.h"
#include "sys/memlayout.h"
#include "sys/types.h"
#include "sys/vm.h"

#include "lib/libc/string.h"

constexpr uintptr_t AP_CODE_LOAD_ADDR = 0x7000;

extern "C" void ap_enter(void)
{
    return;
}

void ap_boot(void)
{
    // generated by the linker for ap_boot binary
    extern uint8_t _binary___build_ap_boot_start[];
    extern uint8_t _binary___build_ap_boot_end[];
    extern uint8_t _binary___build_ap_boot_size[];

    uint8_t *code = reinterpret_cast<decltype(code)>(P2V(AP_CODE_LOAD_ADDR));
    memmove(code, _binary___build_ap_boot_start, (size_t)_binary___build_ap_boot_size);

    
}